version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-standalone
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    restart: unless-stopped
